### ISSUE TITLE
execution mode ignored when using partitions

### ISSUE THREAD

**Issue by ebirn** [reframe-hpc/reframe#2362]
Hi, 

We've noticed today that reframe (3.9.3) seems to ignore execution mode settings when target_systems includes partitions.

Using example config here: https://gist.github.com/ebirn/2f9011b4c3dcd1b1858dacf81d378300
The call below is not listing the mode "part_system"
```
$REFRAME --config-file mode_missing_part.py --show-config modes -vvv
Loading user configuration
Loading configuration file: 'mode_missing_part.py'
Detecting system
Looking for a matching configuration entry for system 'stg-login-0.cbe.staging.clip.vbc.ac.at'
Configuration found: picking system 'abc'
Selecting subconfig for 'abc'
Initializing runtime
Selecting subconfig for 'abc:def'
Initializing system partition 'def'
Selecting subconfig for 'abc'
Initializing system 'abc'
Initializing modules system 'nomod'
[
  {
    "name": "all_systeme",
    "target_systems": [
      "*"
    ],
    "options": [
      "--list"
    ]
  },
  {
    "name": "one_system",
    "target_systems": [
      "abc"
    ],
    "options": [
      "--list"
    ]
  }
]
```

The feature would be useful to us, as we have a development system which is almost identical to the production system, just with a handful of nodes, and some of the partitions missing.

Best,
Erich

**Comment by ebirn** [comment]
In the docs it says "system/partition" https://reframe-hpc.readthedocs.io/en/stable/config_reference.html?highlight=mode#modes-.target_systems 

> A list of systems or system/partitions combinations that this execution mode is valid for.

**Comment by vkarak** [comment]
> A list of systems or system/partitions combinations that this execution mode is valid for.

Hi @ebirn, this is a bug in the documentation. You can't specify a partition for the execution modes. Execution modes are simply collections of command line options, which are practically combined with the passed command line options and then the framework's runtime is configured. At this level, there is no partition information yet.

One solution could be to have only the common options in the execution mode and then pass partition-specific command line options explicitly at invocation. Another one could be to set the configuration parameters that you want to change instead of passing them as command line options with the exec. modes. In this case, you can scope them at partition level.

**Comment by ebirn** [comment]
Hi @vkarak thanks for the explanation.
My use case is this: We have a production system with several partitions i.e. "A", B", "C", "D".
We also have a development system with very similar setup, software tree, programming environments etc. 
The main difference is that it has only a subset of the partitions of the production system i.e. "A" and "C". 

What I would like to do is to run the same set of tests on prod and dev system, without duplicating the reframe config.
So I was looking for a way to select test execution by (multiple) partitions. i.e. A+C.

**Comment by vkarak** [comment]
Hi @ebirn, sorry for the very late reply. Assuming that in your tests you set the `valid_systems` to the partitions of the production system and assuming that those have the same name with your TDS, then you could simply invoke reframe with `--system=prodsys`. This will load the production system configuration and tests will think that they run on the production system. Would that work for you?
