### ISSUE TITLE
`--distribute` option is too slow

### ISSUE THREAD

**Issue by vkarak** [reframe-hpc/reframe#2497]
```
time ./bin/reframe -C config/cscs.py -c cscstests/microbenchmarks/gpu/gpu_burn/gpu_burn_test.py -S num_tasks=1 -J reservation=foo -l
...
real	0m0.734s
user	0m0.509s
sys	0m0.105s
```

```
time ./bin/reframe -C config/cscs.py -c cscstests/microbenchmarks/gpu/gpu_burn/gpu_burn_test.py -S num_tasks=1 -J reservation=foo --distribute=all -l
...
real	0m4.629s
user	0m3.077s
sys	0m0.443s
```

I think that the slowdown is due to the `scontrol`s done behind the scenes, but we need to investigate further and either improve it or add a note in the documentation.

**Comment by ekouts** [comment]
The `scontrol` commands add some delay but the main slowdown comes from somewhere else. It might be because we create too many testcases. In the first case we pass `-Jw=nid02780` and create only one testcase, but in the second case we generate more than 5k testcases.
```bash
time ./bin/reframe -C config/cscs.py -c cscstests/microbenchmarks/gpu/gpu_burn/gpu_burn_test.py -S num_tasks=1 -Jw=nid02780 --distribute=all -l -vvv | grep scontrol
[CMD] 'scontrol -a show -o nodes'
[CMD] 'scontrol -a show -o partitions'
[CMD] 'scontrol -a show -o node nid02780'
[CMD] 'scontrol -a show -o nodes'
[CMD] 'scontrol -a show -o partitions'
[CMD] 'scontrol -a show -o node nid02780'
[CMD] 'scontrol -a show -o nodes'
[CMD] 'scontrol -a show res interact_gpu'
[CMD] 'scontrol -a show -o Nodes=nid0[4135,6914-6917]'
[CMD] 'scontrol -a show -o partitions'
[CMD] 'scontrol -a show -o node nid02780'
[CMD] 'scontrol -a show -o nodes'
[CMD] 'scontrol -a show res interact_mc'
[CMD] 'scontrol -a show -o Nodes=nid0[1576-1579,1597]'
[CMD] 'scontrol -a show -o partitions'
[CMD] 'scontrol -a show -o node nid02780'
[CMD] 'scontrol -a show -o nodes'
[CMD] 'scontrol -a show -o node nid02780'

real	0m4.766s
user	0m3.340s
sys	0m0.544s
```

```bash
time ./bin/reframe -C config/cscs.py -c cscstests/microbenchmarks/gpu/gpu_burn/gpu_burn_test.py -S num_tasks=1  --distribute=all -l -vvv | grep scontrol
[CMD] 'scontrol -a show -o nodes'
[CMD] 'scontrol -a show -o partitions'
[CMD] 'scontrol -a show -o nodes'
[CMD] 'scontrol -a show -o partitions'
[CMD] 'scontrol -a show -o nodes'
[CMD] 'scontrol -a show res interact_gpu'
[CMD] 'scontrol -a show -o Nodes=nid0[4135,6914-6917]'
[CMD] 'scontrol -a show -o partitions'
[CMD] 'scontrol -a show -o nodes'
[CMD] 'scontrol -a show res interact_mc'
[CMD] 'scontrol -a show -o Nodes=nid0[1576-1579,1597]'
[CMD] 'scontrol -a show -o partitions'
[CMD] 'scontrol -a show -o nodes'

real	0m40.938s
user	0m38.965s
sys	0m1.187s
```

**Comment by ekouts** [comment]
The slowdown doesn't come from the `scontrol` command, but from the creation of too many tests. I tried profiling the code with the following command, which listed 5671 tests:
```bash
python -m cProfile -o reframe.prof ./bin/reframe -C ../cscs-reframe-tests/config/cscs.py -c ../cscs-reframe-tests/checks/microbenchmarks/gpu/gpu_burn/gpu_burn_test.py -S num_tasks=1 --distribute=all -l
```
And this is the break down of the time (with `snakeviz reframe.prof`):
<img width="1488" alt="Screenshot 2022-05-30 at 17 00 37" src="https://user-images.githubusercontent.com/6107739/171019701-9fcefbb6-9a4d-40aa-a623-b7b8e51173b2.png">

The bright pink on the second level is the getallnodes method (which calls the `scontrol` commands) and it takes about 4 seconds or 6.18% of the time). Almost 10 seconds are also spent in `list_checks`, but this is because ReFrame prints more than 5k tests in the stdout. Most of the time is actually spent in the test instantiation and generation (~42 seconds) from which ~20 are in deepcopy. 

<img width="1488" alt="Screenshot 2022-05-30 at 17 08 49" src="https://user-images.githubusercontent.com/6107739/171020343-54a1dc58-7da0-4dba-beb0-a0138323a0f0.png">
