### ISSUE TITLE
RFE: new parameter for perflog file name

### ISSUE THREAD

**Issue by flx42** [reframe-hpc/reframe#2591]
This is a follow-up of https://github.com/reframe-hpc/reframe/issues/2577 and the comment https://github.com/reframe-hpc/reframe/pull/2578#issuecomment-1231358999

The request is to have a way to control the filename of the `filelog` output file, in order to have a human-readable filename like `ib_write_bw_loopback_mlx5_6.log` (where `mlx5_6` is a test parameter) when listing files, instead of having `ib_write_bw_loopback_<hash>.log`

In addition to having a way to control the filename, I suppose we also need a way in the ReFrame settings file to stringify the test parameters in order to get a filename similar to what we had in ReFrame 3.x.

Thanks!

**Comment by vkarak** [comment]
Might be addressed by #2670.

**Comment by TomMelt** [comment]
I would also find this useful

**Comment by vkarak** [comment]
I have been giving a thought on this recently and I think having the test hash at test perflog filename is only a limitation; it does not offer anything. The log file would be named as `BaseTestName.log` instead of the current `BaseTestName_<hash>.log` and then log the parameters inside the test by default (through providing a `%(check_params)s` log attribute). The advantage of this is that you will have the data and the parameter values inside the same log file, so post-processing will be much easier. What do you think?

**Comment by flx42** [comment]
Yes I think a single file would be fine.
Thanks!
